//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace member_home.masterRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/assignment3wcfservices")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="masterRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addtocart", ReplyAction="http://tempuri.org/IService1/addtocartResponse")]
        string addtocart(string hotel, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletefromcart", ReplyAction="http://tempuri.org/IService1/deletefromcartResponse")]
        bool deletefromcart(string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getitems", ReplyAction="http://tempuri.org/IService1/getitemsResponse")]
        string getitems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clearcart", ReplyAction="http://tempuri.org/IService1/clearcartResponse")]
        bool clearcart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZipCode", ReplyAction="http://tempuri.org/IService1/GetZipCodeResponse")]
        string GetZipCode(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/credentialCheck", ReplyAction="http://tempuri.org/IService1/credentialCheckResponse")]
        string credentialCheck(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stemmer", ReplyAction="http://tempuri.org/IService1/stemmerResponse")]
        string stemmer(string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        member_home.masterRef.CompositeType GetDataUsingDataContract(member_home.masterRef.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : member_home.masterRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<member_home.masterRef.IService1>, member_home.masterRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addtocart(string hotel, int price) {
            return base.Channel.addtocart(hotel, price);
        }
        
        public bool deletefromcart(string prefix) {
            return base.Channel.deletefromcart(prefix);
        }
        
        public string getitems() {
            return base.Channel.getitems();
        }
        
        public bool clearcart() {
            return base.Channel.clearcart();
        }
        
        public string GetZipCode(string value) {
            return base.Channel.GetZipCode(value);
        }
        
        public string credentialCheck(string username, string password) {
            return base.Channel.credentialCheck(username, password);
        }
        
        public string stemmer(string line) {
            return base.Channel.stemmer(line);
        }
        
        public member_home.masterRef.CompositeType GetDataUsingDataContract(member_home.masterRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
